import React from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Search.module.css';

export async function getServerSideProps({ query }) {
    const response = await fetch(
        `http://localhost:3000/api/searchDrink?s=${query.q}`,
    );
    const results = await response.json();
    return {
        props: {
            results,
        },
    };
}

function Results({ results }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Cocktailmania</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Cocktailmania</h1>

                <p className={styles.description}>For the cocktail lovers</p>

                <ul className={styles.grid}>
                    {results.drinks.length < 1 ? (
                        <h1>Please enter something else</h1>
                    ) : (
                        results.drinks.map((drink) => {
                            const { idDrink, strDrink, strDrinkThumb } = drink;
                            return (
                                <li key={idDrink} className={styles.card}>
                                    <img
                                        className={styles.image}
                                        src={strDrinkThumb}
                                        alt={`${strDrink}`}
                                    />
                                    <Link href={`./drink/${idDrink}`}>
                                        <a>
                                            <h2>{strDrink}</h2>
                                        </a>
                                    </Link>
                                </li>
                            );
                        })
                    )}
                </ul>
            </main>
        </div>
    );
}

Results.propTypes = {
    results: PropTypes.shape({
        drinks: PropTypes.arrayOf(
            PropTypes.shape({
                strDrink: PropTypes.string,
                strDrinkCategory: PropTypes.string,
                strAlcoholic: PropTypes.string,
                strGlass: PropTypes.string,
                strInstructions: PropTypes.string,
                strIngredient1: PropTypes.string,
                strDrinkThumb: PropTypes.string,
                idDrink: PropTypes.string,
            }),
        ),
    }).isRequired,
};

export default Results;
